[2023/02/05] Fix/extension+date difference to string >> 소설 작성 시간 오류 수정
TeamGoodGood/RelayNovel_iOS pull request #147
Opened 2023-02-04 15:12 UTC by ohhseungyeon

## 작업사항
소설 작성 시간과 현재시간 사이의 시간변환 시 생기는 오류를 수정했습니다.
2022년 12월 31일날 작성시 2023년 1월 1일이 되면 1년전으로 표기되는 오류 -> 하루 전
11월 30일 23시 59분 작성시 12월 1일 0시 1분이 되면 한 달 전으로 표기되는 오류 -> 2분 전

## 이슈번호
- #140

## 특이사항(Optional)
작성 시간과 현재 시간의 차이가 1분 미만일 경우 '방금 전'으로 수정했습니다.

close #140

2023-02-09 14:21 UTC, JaewoongLee-swift requested changes
로직에 오류가 있어 수정이 필요해 보입니다.
시간차이가 '~분 전' -> '~시간 전' -> '~일 전' -> '~달 전' -> '~몇년 전' 순서대로 계산되니 날짜차이의 조건의 순서를 다음과 같이 바꾸면 조건처리가 더 유용할 것이라 생각됩니다.

제가 생각하는 순서 또한 정확하지 않을 수 있습니다. 여러 날짜를 테스트해보고 오류를 찾아보면 좋을 것같습니다.

ex) 조건처리 순서
1. 같은 시간 내의 차이인지? 같은 시간 차이를 벗어났다면 그 시간차가 1시간 이내인지?
2. 같은 날 내의 차이인지? 같은 날은 벗어났지만 그 시간차가 24시간보다 작은지?
3. 같은 달 내의 차이인지? 같은 달은 아니지만 31일 내의 차이인지? (또는 30일)
4. 같은 해 내의 차이인지? 같은 해는 아니지만 12개월 내의 차이인지?

2023-02-09 14:21 UTC, JaewoongLee-swift commented on Relay/Relay/Scenes/Extension+/Extension+Double.swift
> +        } else if nowDay - day < 0 {
오늘 202302092309 기준으로 Double 값을 `202212311200`으로 계산하니 '9일 전'으로 출력되었습니다.

```
//오늘 = 202302092309
let date = 202212311200.dateDifferenceToString

print(date) // prints 9일 전
```

날짜계산 로직에서 해당 elseif문으로 빠져나오는 것을 확인했습니다. 로직수정이 필요해보입니다.

2023-02-15 08:09 UTC, ohhseungyeon commented on Relay/Relay/Scenes/Extension+/Extension+Double.swift
> +        } else if nowDay - day < 0 {
확인했습니다! 실행해보니 수정전 로직이 올라간 것 같습니다ㅜ 수정하겠습니다.

2023-02-15 09:20 UTC, ohhseungyeon commented
> 로직에 오류가 있어 수정이 필요해 보입니다. 시간차이가 '~분 전' -> '~시간 전' -> '~일 전' -> '~달 전' -> '~몇년 전' 순서대로 계산되니 날짜차이의 조건의 순서를 다음과 같이 바꾸면 조건처리가 더 유용할 것이라 생각됩니다.
> 
> 제가 생각하는 순서 또한 정확하지 않을 수 있습니다. 여러 날짜를 테스트해보고 오류를 찾아보면 좋을 것같습니다.
> 
> ex) 조건처리 순서
> 
> 1. 같은 시간 내의 차이인지? 같은 시간 차이를 벗어났다면 그 시간차가 1시간 이내인지?
> 2. 같은 날 내의 차이인지? 같은 날은 벗어났지만 그 시간차가 24시간보다 작은지?
> 3. 같은 달 내의 차이인지? 같은 달은 아니지만 31일 내의 차이인지? (또는 30일)
> 4. 같은 해 내의 차이인지? 같은 해는 아니지만 12개월 내의 차이인지?

상세한 피드백 감사합니다:)  조건 처리 순서는 해 > 달 > 날 > 시간 순으로 하였습니다. 차이를 구하려면 각각의 숫자를 비교해야하는데, 예를 들어 글 작성 시간이 2212150423이고 현재 시간이 2302150428일 때 시간을 먼저 비교한다면 시간 > 날 > 달 > 해의 조건을 모두 비교해야하지만 역 순일 시, 해 > 달 > 날까지만 비교해도 2달 전이라는 값이 나오기 때문에 역 순이 더 효율적이라고 판단하여 그대로 사용했습니다. 피드백 덕분에 여러 방면으로 생각해볼 수 있었습니다~!

2023-02-15 09:22 UTC, ohhseungyeon commented on Relay/Relay/Scenes/Extension+/Extension+Double.swift
> +        } else if nowDay - day < 0 {
수정완료했습니다! 수정커밋 : [936ab9b]

2023-02-21 07:51 UTC, JaewoongLee-swift commented
> > 로직에 오류가 있어 수정이 필요해 보입니다. 시간차이가 '~분 전' -> '~시간 전' -> '~일 전' -> '~달 전' -> '~몇년 전' 순서대로 계산되니 날짜차이의 조건의 순서를 다음과 같이 바꾸면 조건처리가 더 유용할 것이라 생각됩니다.
> > 제가 생각하는 순서 또한 정확하지 않을 수 있습니다. 여러 날짜를 테스트해보고 오류를 찾아보면 좋을 것같습니다.
> > ex) 조건처리 순서
> > 
> > 1. 같은 시간 내의 차이인지? 같은 시간 차이를 벗어났다면 그 시간차가 1시간 이내인지?
> > 2. 같은 날 내의 차이인지? 같은 날은 벗어났지만 그 시간차가 24시간보다 작은지?
> > 3. 같은 달 내의 차이인지? 같은 달은 아니지만 31일 내의 차이인지? (또는 30일)
> > 4. 같은 해 내의 차이인지? 같은 해는 아니지만 12개월 내의 차이인지?
> 
> 상세한 피드백 감사합니다:) 조건 처리 순서는 해 > 달 > 날 > 시간 순으로 하였습니다. 차이를 구하려면 각각의 숫자를 비교해야하는데, 예를 들어 글 작성 시간이 2212150423이고 현재 시간이 2302150428일 때 시간을 먼저 비교한다면 시간 > 날 > 달 > 해의 조건을 모두 비교해야하지만 역 순일 시, 해 > 달 > 날까지만 비교해도 2달 전이라는 값이 나오기 때문에 역 순이 더 효율적이라고 판단하여 그대로 사용했습니다. 피드백 덕분에 여러 방면으로 생각해볼 수 있었습니다~! 감사합니다

오히려 큰 단위의 시간순서대로 비교를 하는게 효율적으로 조건처리할 수 있군요! 저도 좋은방법 알아갑니다👍

```
// 기준시간 
var now = 202302211620
// 비교시간들
var difference1  = 202302101200.dateDifferenceToString //11일 전
var difference2  =202301281200.dateDifferenceToString //23일 전
var difference3 = 202301201200.dateDifferenceToString //1달 전
var difference4 = 202301011200.dateDifferenceToString //1달 전
var difference5 = 202212281200.dateDifferenceToString //2달 전
var difference6 = 202212201200.dateDifferenceToString //2달 전
var difference7 = 202203201200.dateDifferenceToString //11달 전
var difference8 = 202202281200.dateDifferenceToString //1년 전
var difference9 = 202202201200.dateDifferenceToString //1년 전
var difference10 = 202103201200.dateDifferenceToString //1년 전
var difference11 = 202102201200.dateDifferenceToString //2년 전
```

다음과 같은 조건으로 테스트해본 결과 모두 정상적으로 계산되서 출력되었습니다!
조건 처리하는게 정말 쉽지 않은 일인데 오류없이 구현하느라 고생 많으셨습니다👍

2023-02-21 07:52 UTC, JaewoongLee-swift approved these changes
조건처리 누락된 부분까지 수정 확인하였습니다!

구현하느라 고생 많으셨습니다 👍

2023-02-22 11:36 UTC, merged