[2023/03/02] Feat/connectZeroContentsView >> 컨텐츠가 없을 때의 화면 디자인 및 로직 구현
TeamGoodGood/RelayNovel_iOS pull request #151
Opened 2023-03-02 06:46 UTC by ohhseungyeon

## 작업사항
**Issue : Feature**
<p align="left">
<img src="https://user-images.githubusercontent.com/70955060/222350967-47ddd573-de1d-47ac-9864-c1345764d849.png" width="15%" height="20%">
<img src="https://user-images.githubusercontent.com/70955060/222351062-f12045a8-e9c1-4f02-890a-9cde43936f2d.png" width="15%" height="20%">
<img src="https://user-images.githubusercontent.com/70955060/222351128-dfcd383f-de22-418a-8ec7-4ee3862ff837.png" width="15%" height="20%">
<img src="https://user-images.githubusercontent.com/70955060/222351177-6ed08443-6c3c-4df1-89f7-dc07bb8d5bd5.png" width="15%" height="20%">
<img src="https://user-images.githubusercontent.com/70955060/222351233-7e023faf-7ab7-4fe0-87a2-d91ab6c94baa.png" width="15%" height="20%">
</p>

알림상세뷰, 둘러보기뷰, 마이페이지(시작한, 참여한, 좋아요한 릴레이) 각각의 뷰에 콘텐츠가 없을 때의 디자인 및 로직을 구현했습니다.

## 이슈번호
- #146

## 특이사항(Optional)

close #146

2023-03-06 07:19 UTC, JaewoongLee-swift approved these changes
간단한 코멘트만 수정해주시면 될 것 같습니다.

extension을 활용한 emptyView 구현 굉장히 유용하네요👍

2023-03-06 07:19 UTC, JaewoongLee-swift commented on Relay/Relay/Scenes/NoticeView/RelayNoticeViewController.swift
>              return 0
noticeArray가 nil인 상황에도 `setEmptyView`를 해주면 좋을것 같습니다.

2023-03-06 07:19 UTC, JaewoongLee-swift commented on Relay/Relay/Scenes/Extension+/Extension+UICollectionView.swift
> +extension UICollectionView {
extension으로 빈 collectionView일 때 간편하게 emptyView를 만들 수 있게 구현한 것이 굉장히 유용한것 같아요👍

2023-03-06 07:19 UTC, JaewoongLee-swift commented on Relay/Relay/Scenes/Extension+/Extension+UITableView.swift
> +extension UITableView {
extension으로 빈 tableView일 때 간편하게 emptyView를 만들 수 있게 구현한 것이 굉장히 유용한것 같아요👍

2023-03-06 07:19 UTC, JaewoongLee-swift commented on Relay/Relay/Scenes/Reusable/RelayListView/RelayListEmptyView.swift
> +extension UICollectionView {
Extension+UICollectionView.swift 파일 내의 UICollectionView extension과 동일한 코드인 것 같습니다. 혹시 중복된 코드 및 파일이 맞다면 해당 파일을 삭제하면 될 것 같습니다.

2023-03-08 08:12 UTC, ohhseungyeon commented on Relay/Relay/Scenes/NoticeView/RelayNoticeViewController.swift
>              return 0
noticeArray타입이 non-optional이라 count값이 0인것으로 대신해주었습니다! 대신 nil값 조건문을 사용했던heightForRowAt 코드를 삭제하고 하나의 return 값을 반환하는 것으로 수정했습니다.

2023-03-08 08:30 UTC, JaewoongLee-swift requested changes
코멘트 재확인 부탁드립니다!

2023-03-08 08:30 UTC, JaewoongLee-swift commented on Relay/Relay/Scenes/NoticeView/RelayNoticeViewController.swift
>              return 0
코멘트와 커밋내용을 확인했는데 `heightForRowAt` 쪽 코드가 수정되었군요. 제가 코멘트를 남긴 부분은 `numberOfRowsInSection` 부분이라 다시한번 확인 부탁드립니다!

2023-03-08 08:41 UTC, ohhseungyeon commented on Relay/Relay/Scenes/NoticeView/RelayNoticeViewController.swift
>              return 0
혹시 noticeArray.count == 0 가 아니라 noticeArray == nil을 쓰는 특별한 이유가 있을까요?? 저는 카운트로도 알림이 없을 때를 충분히 구분할 수 있다고 생각해서 현재 코드대로 작성했는데 nil인 상황을 따로 조건설정해주는 이유가 궁금합니다!

2023-03-08 11:04 UTC, ohhseungyeon commented on Relay/Relay/Scenes/NoticeView/RelayNoticeViewController.swift
>              return 0
피드백 해주신 부분 직관적인 코드로 수정했습니다! (수정커밋 : 080b074)

2023-03-09 00:22 UTC, JaewoongLee-swift approved these changes
확인했습니다! 코멘트대로 수정해주시느라 고생많으셨습니다 :)

2023-03-09 08:06 UTC, merged